name: bachat_gat
description: Bachat gat applicatioon

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  sqflite_common_ffi_web: ^0.4.3+1
  uuid: ^4.4.0
  json_annotation: ^4.8.1
  file_saver: ^0.2.12
  file_picker: ^8.0.0+1
  shared_preferences: ^2.2.2
  pdf: ^3.10.8
  printing: ^5.12.0
  excel: ^4.0.3
  open_filex: ^4.4.0
#  open_file: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
